apiVersion: v1
kind: Pod
metadata:
  name: ns-pod
  namespace: prod
  labels:
    app: mydemo-app
spec:
  containers:
    - name: my-container
      image: nginx:1.29
      ports:
        - containerPort: 80
