apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mytest
spec:
  containers:
    - name: mypod
      image: jenkins/jenkins:lts-alpine
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "300m"
  restartPolicy: Always

