apiVersion: v1
kind: Pod
metadata:
  name: pod-utilization
  labels:
    app: mytest-pod
spec:
  containers:
    - name: mytest-container
      image: jenkins/jenkins:lts
      securityContext:
        runAsUser: 0       # ✅ FORCES ROOT USER
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "300Mi"
          cpu: "2000m"
        limits:
          memory: "600Mi"
          cpu: "500m"
  restartPolicy: Always


