apiVersion: v1
kind: Pod
metadata:
  name: svc-pod-2
  labels:
    app: test-1
spec:
  containers:
    - name: test-co-2
      image: polu8688/java-repo:latest
      ports:
        - containerPort: 8080
          protocol: TCP