apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  namespace: dev
  labels:
    app: javaapp
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: javaapp        # must match template labels
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - name: myjava-container
          image: polu8688/java-repo:latest
          ports:
            - containerPort: 8080     # update if your app uses different port
          livenessProbe:
            tcpSocket:
              port: 80
          resources:
            requests:
              cpu: 125m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
      restartPolicy: Always


                                      
