apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  namespace: dev
  labels:
    app: javaapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: javaapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - name: myjava-container
          image: polu8688/java-repo:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080      
            initialDelaySeconds: 40
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 512Mi  
            limits:
              cpu: 500m
              memory: 1Gi     
      restartPolicy: Always



                                      
