apiVersion: v1
kind: Service
metadata:
  name: javaapp-svc
  namespace: dev
spec:
  selector:
    app: javaapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
   

