apiVersion: v1
kind: Pod
metadata:
  name: static-pod
spec:
  containers:
    - name: container-1
      image: nginx:1.29
      ports:
        - containerPort: 80
          protocol: TCP

    - name: container-2
      image: alpine
      command:
        - "sleep"
        - "5"


    
      